---
collections:
  - name: ansible.controller
    version: 4.4.0
  - name: redhat_cop.controller_configuration
  # linux
  - name: ansible.posix
  - name: redhat.insights
  - name: redhat.rhel_system_roles
  - name: community.general
  - name: containers.podman
  # windows
  - name: chocolatey.chocolatey
  - name: community.windows
  - name: ansible.windows
  # cloud
  - name: azure.azcollection
  - name: amazon.aws
  # satellite
  - name: redhat.satellite
  # network
  - name: cisco.ios
  - name: cisco.nxos
  - name: cisco.iosxr
  - name: ansible.netcommon
  # openshift
  - name: redhat.openshift
  - name: kubernetes.core
